// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2yIUlnUhvan-j7Dq0Mr4u-xOkcZvOJQ8',
    appId: '1:58770683265:web:94fe597a94b05853cde480',
    messagingSenderId: '58770683265',
    projectId: 'scoliofit-8b0d2',
    authDomain: 'scoliofit-8b0d2.firebaseapp.com',
    storageBucket: 'scoliofit-8b0d2.firebasestorage.app',
    measurementId: 'G-Z6LLL7WGTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KC7IZzaW_NL2JJ7rR-xSP29ybAMNS8E',
    appId: '1:58770683265:android:9cc1148393920329cde480',
    messagingSenderId: '58770683265',
    projectId: 'scoliofit-8b0d2',
    storageBucket: 'scoliofit-8b0d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAc7BhrgPoS9y73MSIpqL4L9QMEBoyzso',
    appId: '1:58770683265:ios:e8cda1490bfef1a7cde480',
    messagingSenderId: '58770683265',
    projectId: 'scoliofit-8b0d2',
    storageBucket: 'scoliofit-8b0d2.firebasestorage.app',
    iosBundleId: 'com.example.scoliofit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAc7BhrgPoS9y73MSIpqL4L9QMEBoyzso',
    appId: '1:58770683265:ios:e8cda1490bfef1a7cde480',
    messagingSenderId: '58770683265',
    projectId: 'scoliofit-8b0d2',
    storageBucket: 'scoliofit-8b0d2.firebasestorage.app',
    iosBundleId: 'com.example.scoliofit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2yIUlnUhvan-j7Dq0Mr4u-xOkcZvOJQ8',
    appId: '1:58770683265:web:057c4a1a78e1f702cde480',
    messagingSenderId: '58770683265',
    projectId: 'scoliofit-8b0d2',
    authDomain: 'scoliofit-8b0d2.firebaseapp.com',
    storageBucket: 'scoliofit-8b0d2.firebasestorage.app',
    measurementId: 'G-MH70N5CZRH',
  );

}